# Generated by Django 5.2.1 on 2025-05-21 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0008_alter_reservationstatuslog_admin_in_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservationdetails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='reservations.reservationdetails')),
            ],
        ),
    ]
