# Generated by Django 5.2.1 on 2025-05-28 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reservationdetails',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='reservations.reservationdetails'),
        ),
    ]
