# Generated by Django 5.2 on 2025-05-01 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomlabel', models.CharField(max_length=100, unique=True)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_entries', to='rooms.calendar')),
            ],
            options={
                'unique_together': {('calendar', 'date')},
            },
        ),
        migrations.AddField(
            model_name='calendar',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='rooms.room'),
        ),
        migrations.CreateModel(
            name='TimeReserved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.TimeField()),
                ('ending_time', models.TimeField()),
                ('date_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_reservations', to='rooms.dateentry')),
            ],
        ),
    ]
