# Generated by Django 5.2.1 on 2025-05-28 11:29

import django.db.models.deletion
import reservations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationRoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('letter_of_endorsement', models.FileField(upload_to=reservations.models.endorsement_upload_path, validators=[reservations.models.validate_file_size, reservations.models.validate_file_extension])),
                ('event_name', models.CharField(max_length=20)),
                ('event_description', models.CharField(max_length=255)),
                ('attendee_list', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_room_detail', to='reservations.attendeelist')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Denied')], default='P', max_length=1)),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
                ('admin_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('reservation_room_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_detail', to='reservations.reservationroomdetails')),
                ('reservation_status_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_detail', to='reservations.reservationstatuslog')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=254, validators=[reservations.models.validate_up_email])),
                ('attendee_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='reservations.attendeelist')),
            ],
            options={
                'unique_together': {('attendee_list', 'user')},
            },
        ),
    ]
