# Generated by Django 5.2 on 2025-04-19 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_in_charge', models.IntegerField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Denied')], default='P', max_length=1)),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationRoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('letter_of_endorsement', models.IntegerField()),
                ('event_name', models.CharField(max_length=20)),
                ('event_description', models.CharField(max_length=255)),
                ('attendee_list', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.attendeelist')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.IntegerField()),
                ('reservation_room_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservationroomdetails')),
                ('reservation_status_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservationstatuslog')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('attendee_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='reservations.attendeelist')),
            ],
            options={
                'unique_together': {('attendee_list', 'user')},
            },
        ),
    ]
