# Generated by Django 5.2 on 2025-04-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdetails',
            name='organizer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservationstatuslog',
            name='admin_in_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
