# Generated by Django 5.2 on 2025-05-11 07:29

import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservationroomdetails_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationroomdetails',
            name='letter_of_endorsement',
            field=models.FileField(upload_to=reservations.models.endorsement_upload_path, validators=[reservations.models.validate_file_size, reservations.models.validate_file_extension]),
        ),
    ]
