# Generated by Django 5.2.1 on 2025-05-15 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservationroomdetails_letter_of_endorsement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdetails',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservationdetails',
            name='reservation_room_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_detail', to='reservations.reservationroomdetails'),
        ),
        migrations.AlterField(
            model_name='reservationdetails',
            name='reservation_status_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_detail', to='reservations.reservationstatuslog'),
        ),
        migrations.AlterField(
            model_name='reservationroomdetails',
            name='attendee_list',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_room_detail', to='reservations.attendeelist'),
        ),
    ]
