# Generated by Django 5.2.1 on 2025-05-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_reservationdetails_organizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationroomdetails',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
