# Generated by Django 5.2.1 on 2025-05-17 10:10

import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_reservationroomdetails_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='user',
            field=models.EmailField(max_length=254, validators=[reservations.models.validate_up_email]),
        ),
    ]
